version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: task-managemente-api-db
    pots:
    - "5432:5432"
    environment:
      POSTGRES_DB: task-managemente-api
      POSTGRES_USEr: postgres
      POSTGRES_PASSWORD: 1234